<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataArsipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        Gedung
        DB::table('gedungs')->insert([
            ['nama_gedung' => 'Gedung Teknologi Informasi dan Komputer'],
        ]);
//        Ruang
        DB::table('ruangs')->insert([
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.100', 'nama_ruang' => 'Jurusan Teknologi Informasi dan Komputer'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.101', 'nama_ruang' => 'Lab Telematika'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.102', 'nama_ruang' => 'Lab Sistem Komputer'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.103', 'nama_ruang' => 'Lab Proses Informasi'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.104', 'nama_ruang' => 'Lab Rekayasa Perangkat Lunak'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.105', 'nama_ruang' => 'Lab Big Data'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.106', 'nama_ruang' => 'Lab Proses Otomasi Robot'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.107', 'nama_ruang' => 'Lab Jaringan Komputer'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.108', 'nama_ruang' => 'Lab Desain dan Penerapan Infrastruktur Jaringan'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.109', 'nama_ruang' => 'Lab Keamanan Jaringan'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.110', 'nama_ruang' => 'Lab Keamanan Informasi'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.111', 'nama_ruang' => 'Lab Komputasi Awan'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.112', 'nama_ruang' => 'Lab Internet of Things'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.200A', 'nama_ruang' => 'Koordinator Program Studi'],
            ['gedung_id' => 1, 'kode_ruang' => 'TIK.200B', 'nama_ruang' => 'Ruang Belajar Mandiri'],
        ]);
//        Lemari
        DB::table('lemaris')->insert([
            ['ruang_id' => 1, 'lemari' => 'Lemari L23A'],
            ['ruang_id' => 1, 'lemari' => 'Lemari L23A'],
            ['ruang_id' => 1, 'lemari' => 'Lemari L23A'],
        ]);
//        Rak
        DB::table('raks')->insert([
            ['lemari_id' => 1, 'rak' => 'Rak R1'],
            ['lemari_id' => 1, 'rak' => 'Rak R2'],
            ['lemari_id' => 1, 'rak' => 'Rak R3'],
        ]);
//        Dokumen
        DB::table('dokumens')->insert([
            ['kode_dokumen' => 'DRH', 'nama_dokumen' => 'Daftar Riwayat Hidup'],
            ['kode_dokumen' => 'D2NIP', 'nama_dokumen' => 'Pertimbangan Teknis NIP'],
            ['kode_dokumen' => 'SK-CPNS', 'nama_dokumen' => 'Surat Keputusan CPNS'],
            ['kode_dokumen' => 'SMPT-CPNS', 'nama_dokumen' => 'Surat Pernyataan Melaksanakan Tugas CPNS'],
            ['kode_dokumen' => 'STTPL', 'nama_dokumen' => 'Surat Tanda Tamat Pendidikan dan Pelatihan CPNS'],
            ['kode_dokumen' => 'SK-PNS', 'nama_dokumen' => 'Surat Keputusan PNS'],
            ['kode_dokumen' => 'PENDIDIKAN', 'nama_dokumen' => 'Riwayat pendidikan terakhir'],
            ['kode_dokumen' => 'PANGKAT', 'nama_dokumen' => 'Riwayat kenaikan pangkat terakhir'],
            ['kode_dokumen' => 'JABATAN', 'nama_dokumen' => 'Riwayat jabatan terakhir'],
            ['kode_dokumen' => 'DIKLAT', 'nama_dokumen' => 'Riwayat diklat terakhir'],
            /*
            ['kode_dokumen' => 'AKREDPT', 'nama_dokumen' => 'Akreditasi Program Studi'],
            ['kode_dokumen' => 'APSPPK', 'nama_dokumen' => 'Surat Usul Pemberhentian Atas Permintaan Sendiri sebagai PNS dari PPK'],
            ['kode_dokumen' => 'BALANTIK', 'nama_dokumen' => 'Berita Acara Pelantikan Dalam Jabatan'],
            ['kode_dokumen' => 'BAPNS', 'nama_dokumen' => 'Berita Acara Pengangkatan Sumpah/ Janji PNS'],
            ['kode_dokumen' => 'BASUMPJAB', 'nama_dokumen' => 'Berita Acara Sumpah/Janji/Pelantikan Jabatan atau SPMT (Surat Perintah Melaksanakan Tugas)'],
            ['kode_dokumen' => 'BUKAH', 'nama_dokumen' => 'Buku Nikah'],
            ['kode_dokumen' => 'DAFKEL', 'nama_dokumen' => 'Daftar Keluarga PNS'],
            ['kode_dokumen' => 'DKP', 'nama_dokumen' => 'Data Kepegawaian Perorangan'],
            ['kode_dokumen' => 'DOKPRESTASI', 'nama_dokumen' => 'Bukti Prestasi'],
            ['kode_dokumen' => 'DPCP', 'nama_dokumen' => 'Daftar Perorangan Calon Penerima Pensiun (DPCP)'],
            ['kode_dokumen' => 'DRH', 'nama_dokumen' => 'Daftar Riwayat Hidup'],
            ['kode_dokumen' => 'DRKERJA', 'nama_dokumen' => 'Daftar Riwayat Pekerjaan'],
            ['kode_dokumen' => 'FRMREGKEL', 'nama_dokumen' => 'Formulir Pendaftaran Isteri (2)/Suami/Anak (2)'],
            ['kode_dokumen' => 'IJZAKHIR', 'nama_dokumen' => 'Ijazah dan Transkrip Nilai'],
            ['kode_dokumen' => 'IJZPEND', 'nama_dokumen' => 'Surat Tanda Lulus/ Ijazah Pada Saat CPNS'],
            ['kode_dokumen' => 'KARDAF74', 'nama_dokumen' => 'Kartu Pendaftaran Ulang PNS Tahun 1974'],
            ['kode_dokumen' => 'KETPT', 'nama_dokumen' => 'Keterangan Pangkalan Data DIKTI (FORLAPDIKTI) / Surat Keterangan KOPERTAIS'],
            ['kode_dokumen' => 'KK', 'nama_dokumen' => 'Kartu Keluarga'],
            ['kode_dokumen' => 'KLARIFPAK', 'nama_dokumen' => 'Asli Klarifikasi Penetapan Angka Kredit'],
            ['kode_dokumen' => 'KPE', 'nama_dokumen' => 'Kartu Pegawai / Kartu Pegawai Elektronik'],
            ['kode_dokumen' => 'KTP', 'nama_dokumen' => 'Kartu Tanda Penduduk'],
            ['kode_dokumen' => 'LAMPXXX', 'nama_dokumen' => 'Lampiran XXX (SE. Kepala BKN No. 08/SE/1983)'],
            ['kode_dokumen' => 'LAMPXXXI', 'nama_dokumen' => 'Lampiran XXXI (SE. Kepala BKN No. 08/SE/1983)'],
            ['kode_dokumen' => 'LAPBACKPN', 'nama_dokumen' => 'Laporan Kembalinya PNS yang Hilang'],
            ['kode_dokumen' => 'LAPLHR', 'nama_dokumen' => 'Laporan Kelahiran/Kematian Anak'],
            ['kode_dokumen' => 'LAPLOSTPN', 'nama_dokumen' => 'Laporan Pegawai yang Hilang'],
            ['kode_dokumen' => 'LAPMATI', 'nama_dokumen' => 'Akta Kematian Suami/Istri'],
            ['kode_dokumen' => 'LAPNKH', 'nama_dokumen' => 'Laporan Perkawinan Pertama/Kedua/Ketiga/Perceraian'],
            ['kode_dokumen' => 'LAPTKPEND', 'nama_dokumen' => 'Laporan Peningkatan Pendidikan'],
            ['kode_dokumen' => 'NILAI1THN', 'nama_dokumen' => 'Daftar Nilai Akademik 1 (Satu) Tahun Terakhir'],
            ['kode_dokumen' => 'NILAI2THN', 'nama_dokumen' => 'Daftar Nilai Akademik 2 (Dua) Tahun Terakhir'],
            ['kode_dokumen' => 'NOTAKP', 'nama_dokumen' => 'Nota Usul Kenaikan Pangkat'],
            ['kode_dokumen' => 'NPAKTCLTN', 'nama_dokumen' => 'Nota Persetujuan Pengaktifan Kembali Pasca Cuti Diluar Tanggungan Negara'],
            ['kode_dokumen' => 'NPCLTN', 'nama_dokumen' => 'Nota Persetujuan Cuti Diluar Tanggungan Negara'],
            ['kode_dokumen' => 'NPDPB', 'nama_dokumen' => 'Nota Persetujuan Perbantuan Pada Daerah Otonom/ Instansi Lain'],
            ['kode_dokumen' => 'NPKP', 'nama_dokumen' => 'Nota Persetujuan dan Nota Pertimbangan Teknis Kenaikan Pangkat'],
            ['kode_dokumen' => 'NPMUT', 'nama_dokumen' => 'Nota Persetujuan Mutasi Lain - lain'],
            ['kode_dokumen' => 'NPNIP', 'nama_dokumen' => 'Nota Persetujuan Penetapan NIP'],
            ['kode_dokumen' => 'NPPI', 'nama_dokumen' => 'Nota Persetujuan Pindah Instansi'],
            ['kode_dokumen' => 'NPPMK', 'nama_dokumen' => 'Nota Persetujuan Peninjauan Masa Kerja'],
            ['kode_dokumen' => 'NPWP', 'nama_dokumen' => 'Nomor Pokok Wajib Pajak'],
            ['kode_dokumen' => 'PAK', 'nama_dokumen' => 'Asli Penetapan Angka Kredit Terakhir (pertahun)'],
            ['kode_dokumen' => 'PAK1', 'nama_dokumen' => 'Penetapan Angkat Kredit (PAK) Dasar Pengangkatan'],
            ['kode_dokumen' => 'PICPNS', 'nama_dokumen' => 'Pas Foto PNS'],
            ['kode_dokumen' => 'PICPSNGPNS', 'nama_dokumen' => 'Pas Foto Suami atau Istri PNS'],
            ['kode_dokumen' => 'PINDAHSKP', 'nama_dokumen' => 'Surat Keputusan Pindah SKP di Unit Kerja Baru'],
            ['kode_dokumen' => 'PUPNS', 'nama_dokumen' => 'Hasil Pendataan Ulang PNS (PUPNS 2015)'],
            ['kode_dokumen' => 'REKOMKASN', 'nama_dokumen' => 'Rekomendasi Komisi Aparatur Sipil Negara'],
            ['kode_dokumen' => 'SCERAI', 'nama_dokumen' => 'Surat Izin Untuk Melangsungkan Perceraian'],
            ['kode_dokumen' => 'SERDIK', 'nama_dokumen' => 'Sertifikat Pendidik'],
            ['kode_dokumen' => 'SERDIKLAT', 'nama_dokumen' => 'Sertifikat Diklat/Uji Kompetensi Penjenjangan'],
            ['kode_dokumen' => 'SERLATSAR', 'nama_dokumen' => 'Sertifikat Diklat Dasar (Sesuai Jenjang)'],
            ['kode_dokumen' => 'SGANTI', 'nama_dokumen' => 'Surat Permintaan Penggantian KARPEG (Lampiran XI SE Kepala BAKN No. 01/SE/1975)'],
            ['kode_dokumen' => 'SKAJAR', 'nama_dokumen' => 'Surat Keputusan Pembagian Tugas Mengajar'],
            ['kode_dokumen' => 'SKAKTCLTN', 'nama_dokumen' => 'Surat Keputusan Pengaktifan Kembali Pasca Cuti Diluar Tanggungan Negara'],
            ['kode_dokumen' => 'SKAKTPJBN', 'nama_dokumen' => 'Surat Keputusan Pengangkatan Kembali dari Pemberhentian Sebagai Pejabat Negara'],
            ['kode_dokumen' => 'SKAKTVHENTIS', 'nama_dokumen' => 'Surat Keputusan Pengaktifan Kembali dari Pemberhentian Sementara'],
            ['kode_dokumen' => 'SKALIHJEN', 'nama_dokumen' => 'Surat Keputusan Pengangkatan dalam jenjang Ahli'],
            ['kode_dokumen' => 'SKATASAN', 'nama_dokumen' => 'SK Kenaikan Pangkat Terakhir dan SK Jabatan Atasan Langsung'],
            ['kode_dokumen' => 'SKBAPEK', 'nama_dokumen' => 'Surat Keputusan Bapek Tentang Putusan Banding Administratif'],
            ['kode_dokumen' => 'SKCACAT', 'nama_dokumen' => 'Surat Keputusan Cacat dari Pejabat Pembina Kepegawaian'],
            ['kode_dokumen' => 'SKCLTN', 'nama_dokumen' => 'Surat Keputusan Cuti Diluar Tanggungan Negara'],
            ['kode_dokumen' => 'SKCP', 'nama_dokumen' => 'Surat Keputusan CPNS'],
            ['kode_dokumen' => 'SKDPB', 'nama_dokumen' => 'Surat Keputusan Perbantuan Kepada Daerah Otonom/Instansi Lain'],
            ['kode_dokumen' => 'SKDPKPB', 'nama_dokumen' => 'Surat Keputusan Dipekerjakan/Diperbantukan Pada Daerah Otonom/Instansi Lain'],
            ['kode_dokumen' => 'SKETANKAKT', 'nama_dokumen' => 'Surat Keterangan Pengangkatan Anak'],
            ['kode_dokumen' => 'SKETDUDA', 'nama_dokumen' => 'Surat Keterangan Duda dari Kelurahan/Kecamatan'],
            ['kode_dokumen' => 'SKETHILANG', 'nama_dokumen' => 'Surat Keterangan Kehilangan dari Kepolisian'],
            ['kode_dokumen' => 'SKETMATI', 'nama_dokumen' => 'Surat Keterangan Kematian'],
            ['kode_dokumen' => 'SKETMEDIS', 'nama_dokumen' => 'Surat Keterangan Tim Penguji Kesehatan'],
            ['kode_dokumen' => 'SKHD', 'nama_dokumen' => 'Surat Keputusan Hukuman Disiplin'],
            ['kode_dokumen' => 'SKHENTI', 'nama_dokumen' => 'Surat Keterangan Pemberhentian Dengan Hormat Sebagai PNS'],
            ['kode_dokumen' => 'SKHENTIJF', 'nama_dokumen' => 'Surat Keputusan Pemberhentian Jabatan Fungsional'],
            ['kode_dokumen' => 'SKHENTIPPK', 'nama_dokumen' => 'Surat Keputusan Pemberhentian dari Pejabat Pembina Kepegawaian'],
            ['kode_dokumen' => 'SKHENTIS', 'nama_dokumen' => 'Surat Keputusan Pemberhentian Sementara'],
            ['kode_dokumen' => 'SKHENTISTR', 'nama_dokumen' => 'Surat Keputusan Pemberhentian dari Jabatan Struktural'],
            ['kode_dokumen' => 'SKINPASS', 'nama_dokumen' => 'Surat Keputusan Inpassing Nama Jabatan'],
            ['kode_dokumen' => 'SKIZNBEL', 'nama_dokumen' => 'Surat Keputusan Izin Belajar'],
            ['kode_dokumen' => 'SKJAB', 'nama_dokumen' => 'Surat Keputusan Pengangkatan, Pemindahan dan Pemberhentian Jabatan'],
            ['kode_dokumen' => 'SKJF1', 'nama_dokumen' => 'SK Pengangkatan Pertama Dalam Jabatan Fungsional'],
            ['kode_dokumen' => 'SKJFKEMBALI', 'nama_dokumen' => 'Surat Keputusan Pengangkatan Kembali Jabatan Fungsional'],
            ['kode_dokumen' => 'SKKONVNIP', 'nama_dokumen' => 'Surat Keputusan Konversi NIP'],
            ['kode_dokumen' => 'SKKP', 'nama_dokumen' => 'Surat Keputusan Kenaikan Pangkat Terakhir'],
            ['kode_dokumen' => 'SKKPALL', 'nama_dokumen' => 'Surat Keputusan Kenaikan Pangkat Pertama Hingga Akhir'],
            ['kode_dokumen' => 'SKKPLB', 'nama_dokumen' => 'Surat Keputusan Kenaikan Pangkat Pengabdian'],
            ['kode_dokumen' => 'SKKPPI', 'nama_dokumen' => 'Surat Keputusan Kenaikan Pangkat Penyesuaian Ijazah'],
            ['kode_dokumen' => 'SKLANTIK', 'nama_dokumen' => 'SK Pengangkatan Dalam Jabatan Terakhir dan Surat Pernyataan Pelantikan (2 Dokumen)'],
            ['kode_dokumen' => 'SKMD', 'nama_dokumen' => 'Surat Keputusan Meninggal Dunia'],
            ['kode_dokumen' => 'SKMPP', 'nama_dokumen' => 'Surat Keputusan Masa Persiapan Pensiun'],
            ['kode_dokumen' => 'SKMUT', 'nama_dokumen' => 'Surat Keputusan Mutasi Lain-lain'],
            ['kode_dokumen' => 'SKNAIKJAB', 'nama_dokumen' => 'Surat Keputusan Kenaikan Jabatan'],
            ['kode_dokumen' => 'SKP', 'nama_dokumen' => 'Sasaran Kinerja Pegawai'],
            ['kode_dokumen' => 'SKP1THN', 'nama_dokumen' => 'SKP, Penilaian Capaian SKP dan Penilaian Prestasi Kerja 1 (Satu) Tahun Terakhir'],
            ['kode_dokumen' => 'SKP2THN', 'nama_dokumen' => 'SKP, Penilaian Capaian SKP dan Penilaian Prestasi Kerja 2 (Dua) Tahun Terakhir'],
            ['kode_dokumen' => 'SKPDPB', 'nama_dokumen' => 'Surat Keputusan Penarikan Dari Perbantuan'],
            ['kode_dokumen' => 'SKPDPK', 'nama_dokumen' => 'Surat Keputusan Penarikan Dari Diperkerjakan'],
            ['kode_dokumen' => 'SKPEMBJO', 'nama_dokumen' => 'Surat Keputusan Pembebasan dari Jabatan Organik'],
            ['kode_dokumen' => 'SKPENS', 'nama_dokumen' => 'Surat Keputusan Pensiun'],
            ['kode_dokumen' => 'SKPENYJFT', 'nama_dokumen' => 'Surat Keputusan Penyesuaian Jabatan Fungsional Tertentu'],
            ['kode_dokumen' => 'SKPI', 'nama_dokumen' => 'Surat Keputusan Pindah Instansi'],
            ['kode_dokumen' => 'SKPMK', 'nama_dokumen' => 'Surat Keputusan Peninjauan Masa Kerja'],
            ['kode_dokumen' => 'SKPN', 'nama_dokumen' => 'Surat Keputusan PNS'],
            ['kode_dokumen' => 'SKPNSPKT', 'nama_dokumen' => 'Surat Keputusan Pengangkatan PNS Dalam Pangkat Lokal'],
            ['kode_dokumen' => 'SKPOPPK', 'nama_dokumen' => 'Surat Keputusan PPK Terkait Perampingan Organisasi'],
            ['kode_dokumen' => 'SKPRESTASI', 'nama_dokumen' => 'Surat Keputusan Prestasi dari Pejabat Pembina Kepegawaian'],
            ['kode_dokumen' => 'SKPUT', 'nama_dokumen' => 'Surat Keputusan Pemberian Uang Tunggu'],
            ['kode_dokumen' => 'SKPWK', 'nama_dokumen' => 'Surat Keputusan Pindah Wilayah Kerja'],
            ['kode_dokumen' => 'SKSUAIGPOK', 'nama_dokumen' => 'Surat Keputusan Penyesuaian Gaji Pokok'],
            ['kode_dokumen' => 'SKTDJASA', 'nama_dokumen' => 'Surat Keputusan Tanda Kehormatan/Tanda Jasa'],
            ['kode_dokumen' => 'SKTEWAS', 'nama_dokumen' => 'SK Penetapan Tewas dari Pejabat Pembina Kepegawaian'],
            ['kode_dokumen' => 'SKTGLLHR', 'nama_dokumen' => 'Surat Keputusan Penetapan Tanggal Lahir'],
            ['kode_dokumen' => 'SKTUBEL', 'nama_dokumen' => 'Surat Keputusan Tugas Belajar'],
            ['kode_dokumen' => 'SKUBHNAM', 'nama_dokumen' => 'Surat Keputusan Penggantian/Perubahan Nama'],
            ['kode_dokumen' => 'SLAPHILANG', 'nama_dokumen' => 'Surat Laporan Kehilangan Kartu Identitas Pegawai (KARPEG/KARIS/KARSU)'],
            ['kode_dokumen' => 'SNIKAH', 'nama_dokumen' => 'Surat Nikah PNS'],
            ['kode_dokumen' => 'SNIKAH2', 'nama_dokumen' => 'Legalisir Surat Laporan Perkawinan dan atau Surat Cerai/Meninggal'],
            ['kode_dokumen' => 'SNIKAH3', 'nama_dokumen' => 'Surat Izin Melangsungkan Perkawinan'],
            ['kode_dokumen' => 'SPENGTR', 'nama_dokumen' => 'Surat Pengantar Usulan Instansi'],
            ['kode_dokumen' => 'SPGNTIKRPEG', 'nama_dokumen' => 'Surat Permintaan Penggantian KARPEG'],
            ['kode_dokumen' => 'SPGNTIKRS', 'nama_dokumen' => 'Surat Permintaan Penggantian KARIS/KARSU'],
            ['kode_dokumen' => 'SPHENTIAPS', 'nama_dokumen' => 'Surat Permohonan Berhenti atas Permintaan Sendiri Sebagai PNS'],
            ['kode_dokumen' => 'SPMT', 'nama_dokumen' => 'Surat Perintah Melaksanakan Tugas (SPMT)'],
            ['kode_dokumen' => 'SPPLT', 'nama_dokumen' => 'Surat Perintah Pelaksana Tugas (plt) dari Pejabat Pembina Kepegawaian'],
            ['kode_dokumen' => 'SPTJMPAK', 'nama_dokumen' => 'Surat Pernyataan Tanggung Jawab Mutlak atas Penetapan Penilaian Angka Kredit'],
            ['kode_dokumen' => 'SPXBKN', 'nama_dokumen' => 'Surat Penyataan Lampiran X (SE Kepala BAKN No. 01/SE/1975)'],
            ['kode_dokumen' => 'SPXIBKN', 'nama_dokumen' => 'Surat Pernyataan Lampiran XI (SE Kepala BKN No. 08/SE/1983)'],
            ['kode_dokumen' => 'SRSKK', 'nama_dokumen' => 'Surat Rekomendasi dari Dit. Status dan Kedudukan Kepegawaian'],
            ['kode_dokumen' => 'SRTDISIPLIN', 'nama_dokumen' => 'Surat Pernyataan Disiplin'],
            ['kode_dokumen' => 'SRTPG', 'nama_dokumen' => 'Pencantuman Gelar Pendidikan'],
            ['kode_dokumen' => 'SSJR', 'nama_dokumen' => 'Surat Keterangan Sehat Jasmani dan Rohani'],
            ['kode_dokumen' => 'STLUD', 'nama_dokumen' => 'Surat Tanda Lulus Ujian Dinas'],
            ['kode_dokumen' => 'STLUPKP', 'nama_dokumen' => 'Surat Tanda Lulus Ujian Penyesuaian Kenaikan Pangkat'],
            ['kode_dokumen' => 'STRPIM', 'nama_dokumen' => 'Sertifikat Diklat Kepemimpinan (DIKLATPIM)'],
            ['kode_dokumen' => 'STTPL', 'nama_dokumen' => 'Surat Tanda Tamat Lulus Pendidikan dan Pelatihan (STTPL)'],
            ['kode_dokumen' => 'SUPERAPS', 'nama_dokumen' => 'Surat Permohonan Berhenti Atas Permintaan Sendiri sebagai PNS'],
            ['kode_dokumen' => 'SUPERHD', 'nama_dokumen' => 'Surat Pernyataan Tidak Pernah Dijatuhi HD Tingkat Sedang/Berat'],
            ['kode_dokumen' => 'SUPERHILANG', 'nama_dokumen' => 'Surat Pernyataan Kehilangan Kartu Identitas Pegawai (KARPEG/KARIS/KARSU)'],
            ['kode_dokumen' => 'SUPERJAB', 'nama_dokumen' => 'Surat Pernyataan Menduduki Jabatan'],
            ['kode_dokumen' => 'SUPERPDNA', 'nama_dokumen' => 'Surat Pernyataan Tidak Sedang Menjalani Proses Pidana/Pernah Dipidana'],
            ['kode_dokumen' => 'TLDIKDIN', 'nama_dokumen' => 'Tanda Lulus Mengikuti Pendidikan Kedinasan'],
            ['kode_dokumen' => 'TLDIKPENSUS', 'nama_dokumen' => 'Tanda Lulus Mengikuti Pendidikan dan Pelatihan/Penataran/Kursus'],
            ['kode_dokumen' => 'URAITGS', 'nama_dokumen' => 'Uraian Tugas yang Ditetapkan Pejabat Setingkat Eselon II'],
            */
        ]);
    }
}
