<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataReferensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//        Agama
        DB::table('agamas')->insertOrIgnore([
            ['agama' => 'Islam'],
            ['agama' => 'Kristen'],
            ['agama' => 'Katholik'],
            ['agama' => 'Hindu'],
            ['agama' => 'Budha'],
            ['agama' => 'Konghucu'],
            ['agama' => 'Lainnya'],
        ]);

//        Tingkat Pendidikan
        DB::table('tingkat_pendidikans')->insertOrIgnore([
            ['id' => 5, 'tingkat_pendidikan' => 'Sekolah Dasar', 'group_tingkat_pendidikan' => 'SD/MI'],
            ['id' => 10, 'tingkat_pendidikan' => 'SLTP', 'group_tingkat_pendidikan' => 'SLTP/MTs'],
            ['id' => 12, 'tingkat_pendidikan' => 'SLTP Kejuruan', 'group_tingkat_pendidikan' => 'SLTP/MTs'],
            ['id' => 15, 'tingkat_pendidikan' => 'SLTA', 'group_tingkat_pendidikan' => 'SLTA/SMK/MA/D-I'],
            ['id' => 17, 'tingkat_pendidikan' => 'SLTA Kejuruan', 'group_tingkat_pendidikan' => 'SLTA/SMK/MA/D-I'],
            ['id' => 18, 'tingkat_pendidikan' => 'SLTA Keguruan', 'group_tingkat_pendidikan' => 'SLTA/SMK/MA/D-I'],
            ['id' => 20, 'tingkat_pendidikan' => 'Diploma I', 'group_tingkat_pendidikan' => 'SLTA/SMK/MA/D-I'],
            ['id' => 25, 'tingkat_pendidikan' => 'Diploma II', 'group_tingkat_pendidikan' => 'D-II'],
            ['id' => 30, 'tingkat_pendidikan' => 'Diploma III/Sarjana Muda', 'group_tingkat_pendidikan' => 'D-III'],
            ['id' => 35, 'tingkat_pendidikan' => 'Diploma IV', 'group_tingkat_pendidikan' => 'S-1/D-IV'],
            ['id' => 40, 'tingkat_pendidikan' => 'S-1/Sarjana', 'group_tingkat_pendidikan' => 'S-1/D-IV'],
            ['id' => 45, 'tingkat_pendidikan' => 'S-2', 'group_tingkat_pendidikan' => 'S-2'],
            ['id' => 50, 'tingkat_pendidikan' => 'S-3/Doktor', 'group_tingkat_pendidikan' => 'S-3'],
        ]);

//          Perguruan Tinggi
        DB::table('perguruan_tinggis')->insertOrIgnore([
            ['perguruan_tinggi' => 'Universitas Gadjah Mada'],
            ['perguruan_tinggi' => 'Universitas Syiah Kuala'],
            ['perguruan_tinggi' => 'Universitas Indonesia'],
            ['perguruan_tinggi' => 'Institut Teknologi Bandung'],
            ['perguruan_tinggi' => 'Institut Teknologi Sepuluh Nopember'],
            ['perguruan_tinggi' => 'Institut Pertanian Bogor'],
            ['perguruan_tinggi' => 'Universitas Padjajaran'],
            ['perguruan_tinggi' => 'Universitas Diponegoro'],
            ['perguruan_tinggi' => 'Universitas Airlangga'],
            ['perguruan_tinggi' => 'Universitas Brawijaya'],
            ['perguruan_tinggi' => 'Universitas Hasanuddin'],
            ['perguruan_tinggi' => 'Universitas Malikussaleh'],
            ['perguruan_tinggi' => 'Universitas Sumatera Utara'],
            ['perguruan_tinggi' => 'Universitas Riau'],
            ['perguruan_tinggi' => 'Universitas Sriwijaya'],
            ['perguruan_tinggi' => 'Universitas Jambi'],
            ['perguruan_tinggi' => 'Universitas Bengkulu'],
            ['perguruan_tinggi' => 'Universitas Lampung'],
            ['perguruan_tinggi' => 'Politeknik Negeri Lhokseumawe'],
        ]);


//        Pendidikan
        DB::table('pendidikans')->insertOrIgnore([
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Komputer', 'perguruan_tinggi_id' => 1],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Komputer', 'perguruan_tinggi_id' => 1],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Komunikasi Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Kimia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Mesin', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Sipil', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Teknik Mesin', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Elektro', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Teknik Kimia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pendidikan Bahasa dan Sastra Indonesia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pendidikan Bahasa Inggris', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Kimia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Teknik Sipil', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Teknik Industri Pertanian', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pengelolaan SDA dan Lingkungan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ekonomi Pembangunan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknologi Informasi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Ekonomi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Ekonomi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Mesin Pertanian', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Keteknikan Pertanian', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Manajemen', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Teknologi Industri Pertanian', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Akuntansi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Manajemen', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Curriculum And Instruction', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Teknik', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Lingkungan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Ekonomi Pertanian', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teologi (Agama Islam)', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Matematika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Kimia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Manajemen', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pendidikan Agama Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Ekonomi dan Studi Pembangunan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Agricultural Science', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ekonomi Syariah', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Material', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Akuntansi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Hukum Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknologi Pangan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Control System Engineering', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Electrical and Computer Engineering', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Engineering', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Fisika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Perminyakan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Statistika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Kimia Analisis', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 National Transnational and Global Contexts', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teaching English To Speakers Of Other Languages', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Hukum', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Ilmu Linguistik', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Telecommunications and Networking', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Natural Resource Management', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Bahasa Inggris', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pendidikan Kewarganegaraan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Mesin Konversi Energi', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Agama Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ekonomi Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Informatika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Pendidikan Pancasila Dan Kewarganegaraan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Elektro Jaringan Cerdas Multimedia', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Electrical Engineering and Computer Science', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Komputer Sains', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Rekayasa Infrastruktur', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Ilmu Informatika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Industri', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Fisika', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S-2 Teknik Energi Terbarukan', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Engineering', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S-3 Hukum Islam', 'perguruan_tinggi_id' => 2],
            ['tingkat_pendidikan_id' => 5, 'pendidikan' => 'SD', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 10, 'pendidikan' => 'SMP', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 15, 'pendidikan' => 'SMA', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 30, 'pendidikan' => 'D3', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 35, 'pendidikan' => 'D4', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 40, 'pendidikan' => 'S1', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 45, 'pendidikan' => 'S2', 'perguruan_tinggi_id' => null],
            ['tingkat_pendidikan_id' => 50, 'pendidikan' => 'S3', 'perguruan_tinggi_id' => null],
        ]);

//        Jurusan
        DB::table('jurusans')->insertOrIgnore([
            ['jurusan' => 'Teknik Sipil'],
            ['jurusan' => 'Teknik Kimia'],
            ['jurusan' => 'Teknik Mesin'],
            ['jurusan' => 'Teknik Elektro'],
            ['jurusan' => 'Bisnis'],
            ['jurusan' => 'Teknologi Informasi dan Komputer'],
        ]);

//        Program Studi
        DB::table('program_studis')->insertOrIgnore([
//            Teknik Sipil
            ['kode_prodi' => '22303', 'status' => 'Aktif', 'jurusan_id' => 1, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Konstruksi Bangunan Gedung'],
            ['kode_prodi' => '22302', 'status' => 'Aktif', 'jurusan_id' => 1, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Konstruksi Jalan dan Jembatan'],
            ['kode_prodi' => '22404', 'status' => 'Aktif', 'jurusan_id' => 1, 'jenjang' => 'D3', 'akreditasi' => 'C', 'nama_prodi' => 'Teknologi Konstruksi Bangunan Air'],
            ['kode_prodi' => '22405', 'status' => 'Aktif', 'jurusan_id' => 1, 'jenjang' => 'D3', 'akreditasi' => 'Baik', 'nama_prodi' => 'Teknologi Konstruksi Jalan dan Jembatan'],
//            Teknik Kimia
            ['kode_prodi' => '24301', 'status' => 'Aktif', 'jurusan_id' => 2, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Kimia Industri'],
            ['kode_prodi' => '32402', 'status' => 'Aktif', 'jurusan_id' => 2, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Pengolahan Minyak dan Gas'],
            ['kode_prodi' => '24401', 'status' => 'Aktif', 'jurusan_id' => 2, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Kimia'],
            ['kode_prodi' => '24305', 'status' => 'Aktif', 'jurusan_id' => 2, 'jenjang' => 'D4', 'akreditasi' => '-', 'nama_prodi' => 'Teknologi Rekayasa Kimia Berkelanjutan'],
//            Teknik Mesin
            ['kode_prodi' => '36303', 'status' => 'Aktif', 'jurusan_id' => 3, 'jenjang' => 'D4', 'akreditasi' => 'Baik', 'nama_prodi' => 'Teknologi Rekayasa Pengelasan dan Fabrikasi'],
            ['kode_prodi' => '21301', 'status' => 'Aktif', 'jurusan_id' => 3, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Manufaktur'],
            ['kode_prodi' => '21401', 'status' => 'Aktif', 'jurusan_id' => 3, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Mesin'],
            ['kode_prodi' => '21402', 'status' => 'Aktif', 'jurusan_id' => 3, 'jenjang' => 'D3', 'akreditasi' => 'C', 'nama_prodi' => 'Teknologi Industri'],
//            Teknik Elektro
            ['kode_prodi' => '20302', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D4', 'akreditasi' => 'Baik', 'nama_prodi' => 'Teknologi Rekayasa Jaringan Telekomunikasi'],
            ['kode_prodi' => '21312', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D4', 'akreditasi' => 'Baik', 'nama_prodi' => 'Teknologi Rekayasa Mekatronika'],
            ['kode_prodi' => '20301', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Instrumentasi dan Kontrol'],
            ['kode_prodi' => '20305', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D4', 'akreditasi' => 'C', 'nama_prodi' => 'Teknologi Rekayasa Pembangkit Energi'],
            ['kode_prodi' => '20401', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Elektronika'],
            ['kode_prodi' => '20403', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Listrik'],
            ['kode_prodi' => '20402', 'status' => 'Aktif', 'jurusan_id' => 4, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Telekomunikasi'],
//            Tata Niaga / Bisnis (BN)
            ['kode_prodi' => '60106', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'S2 Terapan', 'akreditasi' => 'Baik', 'nama_prodi' => 'Keuangan Islam Terapan'],
            ['kode_prodi' => '61306', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Akuntansi Lembaga Keuangan Syariah'],
            ['kode_prodi' => '62303', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D4', 'akreditasi' => 'Baik', 'nama_prodi' => 'Akuntansi Sektor Publik'],
            ['kode_prodi' => '61312', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D4', 'akreditasi' => '-', 'nama_prodi' => 'Manajemen Keuangan Sektor Publik'],
            ['kode_prodi' => '63411', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Administrasi Bisnis'],
            ['kode_prodi' => '62401', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Akuntansi'],
            ['kode_prodi' => '61406', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D3', 'akreditasi' => 'B', 'nama_prodi' => 'Perbankan Dan Keuangan'],
            ['kode_prodi' => '79308', 'status' => 'Aktif', 'jurusan_id' => 5, 'jenjang' => 'D4', 'akreditasi' => '-', 'nama_prodi' => 'Bahasa Inggris untuk Komunikasi Bisnis dan Profesional'],
//            TIK
            ['kode_prodi' => '57301', 'status' => 'Aktif', 'jurusan_id' => 6, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknik Informatika'],
            ['kode_prodi' => '90343', 'status' => 'Aktif', 'jurusan_id' => 6, 'jenjang' => 'D4', 'akreditasi' => 'B', 'nama_prodi' => 'Teknologi Rekayasa Komputer Jaringan'],
            ['kode_prodi' => '58302', 'status' => 'Aktif', 'jurusan_id' => 6, 'jenjang' => 'D4', 'akreditasi' => 'Baik', 'nama_prodi' => 'Teknologi Rekayasa Multimedia'],
            ['kode_prodi' => '58305', 'status' => 'Aktif', 'jurusan_id' => 6, 'jenjang' => 'D4', 'akreditasi' => '-', 'nama_prodi' => 'Teknologi Rekayasa Perangkat Lunak'],
        ]);

//        Eselon
        DB::table('eselons')->insertOrIgnore([
            ['id' => '00', 'eselon' => '', 'eselon_level' => '0', 'jabatan_asn' => ''],
            ['id' => '10', 'eselon' => 'I.a', 'eselon_level' => '1', 'jabatan_asn' => 'JABATAN PIMPINAN TINGGI UTAMA'],
            ['id' => '11', 'eselon' => 'I.a', 'eselon_level' => '1', 'jabatan_asn' => 'JABATAN PIMPINAN TINGGI MADYA'],
            ['id' => '12', 'eselon' => 'I.b', 'eselon_level' => '1', 'jabatan_asn' => 'JABATAN PIMPINAN TINGGI MADYA'],
            ['id' => '21', 'eselon' => 'II.a', 'eselon_level' => '2', 'jabatan_asn' => 'JABATAN PIMPINAN TINGGI PRATAMA'],
            ['id' => '22', 'eselon' => 'II.b', 'eselon_level' => '2', 'jabatan_asn' => 'JABATAN PIMPINAN TINGGI PRATAMA'],
            ['id' => '31', 'eselon' => 'III.a', 'eselon_level' => '3', 'jabatan_asn' => 'JABATAN ADMINISTRATOR'],
            ['id' => '32', 'eselon' => 'III.b', 'eselon_level' => '3', 'jabatan_asn' => 'JABATAN ADMINISTRATOR'],
            ['id' => '41', 'eselon' => 'IV.a', 'eselon_level' => '4', 'jabatan_asn' => 'JABATAN PENGAWAS'],
            ['id' => '42', 'eselon' => 'IV.b', 'eselon_level' => '4', 'jabatan_asn' => 'JABATAN PENGAWAS'],
            ['id' => '51', 'eselon' => 'V.a', 'eselon_level' => '5', 'jabatan_asn' => null],
            ['id' => '52', 'eselon' => 'V.b', 'eselon_level' => '5', 'jabatan_asn' => null],
            ['id' => '99', 'eselon' => 'Non Eselon', 'eselon_level' => 'Non Eselon', 'jabatan_asn' => null],
        ]);

//        Pangkat
        DB::table('pangkats')->insertOrIgnore([
            ['id' => '11', 'golongan_ruang' => 'I/a', 'pangkat' => 'Juru Muda'],
            ['id' => '12', 'golongan_ruang' => 'I/b', 'pangkat' => 'Juru Muda Tingkat I'],
            ['id' => '13', 'golongan_ruang' => 'I/c', 'pangkat' => 'Juru'],
            ['id' => '14', 'golongan_ruang' => 'I/d', 'pangkat' => 'Juru Tingkat I'],
            ['id' => '21', 'golongan_ruang' => 'II/a', 'pangkat' => 'Pengatur Muda'],
            ['id' => '22', 'golongan_ruang' => 'II/b', 'pangkat' => 'Pengatur Muda Tingkat I'],
            ['id' => '23', 'golongan_ruang' => 'II/c', 'pangkat' => 'Pengatur'],
            ['id' => '24', 'golongan_ruang' => 'II/d', 'pangkat' => 'Pengatur Tingkat I'],
            ['id' => '31', 'golongan_ruang' => 'III/a', 'pangkat' => 'Penata Muda'],
            ['id' => '32', 'golongan_ruang' => 'III/b', 'pangkat' => 'Penata Muda Tingkat I'],
            ['id' => '33', 'golongan_ruang' => 'III/c', 'pangkat' => 'Penata'],
            ['id' => '34', 'golongan_ruang' => 'III/d', 'pangkat' => 'Penata Tingkat I'],
            ['id' => '41', 'golongan_ruang' => 'IV/a', 'pangkat' => 'Pembina'],
            ['id' => '42', 'golongan_ruang' => 'IV/b', 'pangkat' => 'Pembina Tingkat I'],
            ['id' => '43', 'golongan_ruang' => 'IV/c', 'pangkat' => 'Pembina Utama Muda'],
            ['id' => '44', 'golongan_ruang' => 'IV/d', 'pangkat' => 'Pembina Utama Madya'],
            ['id' => '45', 'golongan_ruang' => 'IV/e', 'pangkat' => 'Pembina Utama'],
            ['id' => '51', 'pangkat' => 'PPPK', 'golongan_ruang' => 'I'],
            ['id' => '52', 'pangkat' => 'PPPK', 'golongan_ruang' => 'II'],
            ['id' => '53', 'pangkat' => 'PPPK', 'golongan_ruang' => 'III'],
            ['id' => '54', 'pangkat' => 'PPPK', 'golongan_ruang' => 'IV'],
            ['id' => '55', 'pangkat' => 'PPPK', 'golongan_ruang' => 'V'],
            ['id' => '56', 'pangkat' => 'PPPK', 'golongan_ruang' => 'VI'],
            ['id' => '57', 'pangkat' => 'PPPK', 'golongan_ruang' => 'VII'],
            ['id' => '58', 'pangkat' => 'PPPK', 'golongan_ruang' => 'VIII'],
            ['id' => '59', 'pangkat' => 'PPPK', 'golongan_ruang' => 'IX'],
            ['id' => '60', 'pangkat' => 'PPPK', 'golongan_ruang' => 'X'],
        ]);

//        Jenis Jabatan
        DB::table('jenis_jabatans')->insertOrIgnore([
            ['id' => 1, 'jenis_jabatan' => 'Jabatan Struktural'],
            ['id' => 2, 'jenis_jabatan' => 'Jabatan Fungsional Tertentu'],
            ['id' => 3, 'jenis_jabatan' => 'Jabatan Rangkap (Struktural dan Fungsional)'],
            ['id' => 4, 'jenis_jabatan' => 'Jabatan Fungsional Umum'],
        ]);

//        Jabatan (Fungsional & Pelaksana)
        DB::table('jabatans')->insertOrIgnore([
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 9, 'pangkat_minimal' => 32, 'jabatan' => 'Asisten Ahli'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 10, 'pangkat_minimal' => 33, 'jabatan' => 'Lektor'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Lektor Kepala'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 14, 'pangkat_minimal' => 44, 'jabatan' => 'Profesor'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 6, 'pangkat_minimal' => 22, 'jabatan' => 'Teknisi Laboratorium'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 21, 'jabatan' => 'Pengadministrasi Umum'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Informasi Akademik'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Pranata Laboratorium Pendidikan Ahli Muda'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 1, 'pangkat_minimal' => 11, 'jabatan' => 'Pramu Bakti'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Penyusun Program Pengembangan Kemahasiswaan'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Kepegawaian'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 21, 'jabatan' => 'Pengadministrasi Persuratan'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 8, 'pangkat_minimal' => 33, 'jabatan' => 'Pranata Laboratorium Pendidikan Penyelia'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 21, 'jabatan' => 'Pengadministrasi Akademik'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Analis Laporan Akuntabilitas Kinerja'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Analis Barang Milik Negara'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 8, 'pangkat_minimal' => 31, 'jabatan' => 'Pranata Laboratorium Pendidikan Ahli Pertama'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 3, 'pangkat_minimal' => 12, 'jabatan' => 'Pengemudi'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 8, 'pangkat_minimal' => 33, 'jabatan' => 'Pustakawan Penyelia'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 11, 'pangkat_minimal' => 41, 'jabatan' => 'Pranata Laboratorium Pendidikan Ahli Madya'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 21, 'jabatan' => 'Pengadministrasi Perpustakaan'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Kemahasiswaan/Alumni'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Keuangan'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Pustakawan Ahli Muda'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Pranata Laboratorium Pendidikan Mahir'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 22, 'jabatan' => 'Pengolah Data'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Analis Tata Laksana'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Analis Sumber Daya Manusia Aparatur Ahli Muda'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Penyusun Bahan Informasi dan Publikasi'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Pengembangan Pembelajaran dan Penjaminan Mutu Pendidikan'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Barang Milik Negara'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Penyusun Laporan Keuangan'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Bendahara Pengeluaran'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Analis Monitoring, Evaluasi dan Pelaporan'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Analis Sumber Daya Manusia Aparatur'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Bendahara Penerimaan'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 6, 'pangkat_minimal' => 22, 'jabatan' => 'Pranata Laboratorium Pendidikan Terampil'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Penyusun Program Anggaran dan Pelaporan'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Pranata Komputer Ahli Muda'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 8, 'pangkat_minimal' => 31, 'jabatan' => 'Pranata Komputer Ahli Pertama'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Disiplin Pegawai'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Gaji'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 21, 'jabatan' => 'Pengadministrasi Perkantoran'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Umum Operasional'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 6, 'pangkat_minimal' => 24, 'jabatan' => 'Pengelola Layanan Operasional'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 7, 'pangkat_minimal' => 31, 'jabatan' => 'Penata Layanan Operasional'],
            ['jenis_jabatan_id' => 4, 'kelas_jabatan' => 5, 'pangkat_minimal' => 22, 'jabatan' => 'Operator Layanan Operasional'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 8, 'pangkat_minimal' => 31, 'jabatan' => 'Pranata Hubungan Masyarakat Ahli Pertama'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 6, 'pangkat_minimal' => 22, 'jabatan' => 'Arsiparis Terampil'],
            ['jenis_jabatan_id' => 2, 'kelas_jabatan' => 6, 'pangkat_minimal' => 22, 'jabatan' => 'Asisten Perpustakaan Terampil'],
        ]);

//        Jabatan (Struktural)
        DB::table('jabatans')->insertOrIgnore([
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 15, 'pangkat_minimal' => 44, 'jabatan' => 'Direktur'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 14, 'pangkat_minimal' => 43, 'jabatan' => 'Wakil Direktur Bidang Akademik dan Sistem Informasi'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 14, 'pangkat_minimal' => 43, 'jabatan' => 'Wakil Direktur Bidang Keuangan dan Umum'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 14, 'pangkat_minimal' => 43, 'jabatan' => 'Wakil Direktur Bidang Kemahasiswaan dan Alumni'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 14, 'pangkat_minimal' => 43, 'jabatan' => 'Wakil Direktur Bidang Perencanaan dan Kerja Sama'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Kepala Bagian Akademik, Kemahasiswaan, dan Alumni'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Kepala Bagian Perencanaan, Keuangan, dan Umum'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Kepala Subbagian Akademik'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 9, 'pangkat_minimal' => 33, 'jabatan' => 'Kepala Subbagian Umum'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Teknik Sipil'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Teknik Kimia'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Teknik Mesin'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Teknik Elektro'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Bisnis'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Ketua Jurusan Teknologi Informasi dan Komputer'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Kepala Pusat Penelitian dan Pengabdian Kepada Masyarakat'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 12, 'pangkat_minimal' => 41, 'jabatan' => 'Kepala Pusat Penjaminan Mutu dan Pengembangan Pembelajaran'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Perpustakaan'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Teknologi Informasi dan Komunikasi'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Bahasa'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Perawatan dan Perbaikan'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Layanan Uji Kompetensi'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Pengembangan Karir dan Kemahasiswa'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 11, 'pangkat_minimal' => 34, 'jabatan' => 'Kepala UPA Pengembangan Teknologi dan Produk Unggulan'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 14, 'pangkat_minimal' => 43, 'jabatan' => 'Ketua Senat'],
            ['jenis_jabatan_id' => 1, 'kelas_jabatan' => 13, 'pangkat_minimal' => 42, 'jabatan' => 'Ketua Satuan Pengawasan Internal'],
        ]);

//        Status Perkawinan
        DB::table('status_perkawinans')->insertOrIgnore([
            ['status_perkawinan' => 'Menikah'],
            ['status_perkawinan' => 'Cerai'],
            ['status_perkawinan' => 'Janda/Duda'],
            ['status_perkawinan' => 'Belum Kawin'],
        ]);

//        Kedudukan Pegawai
        DB::table('kedudukan_pegawais')->insertOrIgnore([
            ['id' => '01', 'kedudukan_pegawai' => 'Aktif'],
            ['id' => '02', 'kedudukan_pegawai' => 'CLTN'],
            ['id' => '03', 'kedudukan_pegawai' => 'Tugas Belajar'],
            ['id' => '04', 'kedudukan_pegawai' => 'Pemberhentian Sementara'],
            ['id' => '05', 'kedudukan_pegawai' => 'Penerima Uang Tunggu'],
            ['id' => '06', 'kedudukan_pegawai' => 'Prajurit Wajib'],
            ['id' => '07', 'kedudukan_pegawai' => 'Pejabat Negara'],
            ['id' => '08', 'kedudukan_pegawai' => 'Kepala Desa'],
            ['id' => '09', 'kedudukan_pegawai' => 'Sedang dlm Proses Banding BAPEK'],
            ['id' => '11', 'kedudukan_pegawai' => 'Pegawai Titipan'],
            ['id' => '12', 'kedudukan_pegawai' => 'Pengungsi'],
            ['id' => '13', 'kedudukan_pegawai' => 'Perpanjangan CLTN'],
            ['id' => '14', 'kedudukan_pegawai' => 'PNS yang dinyatakan hilang'],
            ['id' => '15', 'kedudukan_pegawai' => 'PNS kena hukuman disiplin'],
            ['id' => '16', 'kedudukan_pegawai' => 'Pemindahan dalam rangka penurunan Jabatan'],
            ['id' => '20', 'kedudukan_pegawai' => 'Masa Persiapan Pensiun'],
            ['id' => '51', 'kedudukan_pegawai' => 'CPNS yang belum menerima SK CPNS'],
            ['id' => '52', 'kedudukan_pegawai' => 'Tidak Aktif'],
            ['id' => '66', 'kedudukan_pegawai' => 'Diberhentikan'],
            ['id' => '67', 'kedudukan_pegawai' => 'Punah'],
            ['id' => '68', 'kedudukan_pegawai' => 'Eks PNS Timor Timur'],
            ['id' => '69', 'kedudukan_pegawai' => 'TMS Dari Pengadaan'],
            ['id' => '70', 'kedudukan_pegawai' => 'Pembatalan NIP'],
            ['id' => '77', 'kedudukan_pegawai' => 'Pemberhentian tanpa hak pensiun'],
            ['id' => '71', 'kedudukan_pegawai' => 'PPPK Aktif'],
            ['id' => '88', 'kedudukan_pegawai' => 'Pemberhentian dengan hak pensiun'],
            ['id' => '89', 'kedudukan_pegawai' => 'Tidak aktif tetapi diusulkan Pensiun'],
            ['id' => '90', 'kedudukan_pegawai' => 'Tidak Ikut PUPNS 2015'],
            ['id' => '91', 'kedudukan_pegawai' => 'Tindak Pidana/ Tindak Pidana Jabatan'],
            ['id' => '92', 'kedudukan_pegawai' => 'Pemblokiran Data PNS'],
            ['id' => '98', 'kedudukan_pegawai' => 'Mencapai BUP'],
            ['id' => '99', 'kedudukan_pegawai' => 'Pensiun'],
        ]);



//        Unit Kerja
        DB::table('unit_kerjas')->insertOrIgnore([
            ['order' => 1, 'unit_kerja' => 'Politeknik Negeri Lhokseumawe'],
            ['order' => 8, 'unit_kerja' => 'Bagian Akademik, Kemahasiswaan, dan Alumni'],
            ['order' => 9, 'unit_kerja' => 'Bagian Perencanaan, Keuangan, dan Umum'],
            ['order' => 10, 'unit_kerja' => 'Subbagian Akademik'],
            ['order' => 11, 'unit_kerja' => 'Subbagian Umum'],
            ['order' => 12, 'unit_kerja' => 'Jurusan Teknik Sipil'],
            ['order' => 13, 'unit_kerja' => 'Jurusan Teknik Kimia'],
            ['order' => 14, 'unit_kerja' => 'Jurusan Teknik Mesin'],
            ['order' => 15, 'unit_kerja' => 'Jurusan Teknik Elektro'],
            ['order' => 16, 'unit_kerja' => 'Jurusan Bisnis'],
            ['order' => 17, 'unit_kerja' => 'Jurusan Teknologi Informasi dan Komputer'],
            ['order' => 18, 'unit_kerja' => 'Pusat Penelitian dan Pengabdian Kepada Masyarakat'],
            ['order' => 19, 'unit_kerja' => 'Pusat Penjaminan Mutu dan Pengembangan Pembelajaran'],
            ['order' => 20, 'unit_kerja' => 'UPA Perpustakaan'],
            ['order' => 21, 'unit_kerja' => 'UPA Teknologi Informasi dan Komunikasi'],
            ['order' => 22, 'unit_kerja' => 'UPA Bahasa'],
            ['order' => 23, 'unit_kerja' => 'UPA Perawatan dan Perbaikan'],
            ['order' => 24, 'unit_kerja' => 'UPA Layanan Uji Kompetensi'],
            ['order' => 25, 'unit_kerja' => 'UPA Pengembangan Karir dan Kemahasiswaan'],
            ['order' => 26, 'unit_kerja' => 'UPA Pengembangan Teknologi dan Produk Unggulan'],
            ['order' => 2, 'unit_kerja' => 'Bidang Akademik dan Sistem Informasi'],
            ['order' => 3, 'unit_kerja' => 'Bidang Keuangan dan Umum'],
            ['order' => 4, 'unit_kerja' => 'Bidang Kemahasiswaan dan Alumni'],
            ['order' => 5, 'unit_kerja' => 'Bidang Perencanaan dan Kerja Sama'],
            ['order' => 6, 'unit_kerja' => 'Senat'],
            ['order' => 7, 'unit_kerja' => 'Satuan Pengawas Internal'],
        ]);
    }
}